language: python
python:
  - 2.7
  - 3.6
notifications:
  email:
    recipients:
      - commits+travis@carbonlighthouse.com
install:
  - pip install -r requirements.txt
#  - pip install coveralls
script:
  - pycodestyle click_tester test
  - coverage run --source=click_tester -m unittest discover -b
#after_success:
#  - coveralls
